#!/bin/bash

set -e

# web-area is a persistent volume - good place for our cache
BASE_DIR=/var/lib/gwms-frontend/web-area/scitoken-testing
mkdir -p $BASE_DIR

ALL=$BASE_DIR/all.txt
ALLOW=$BASE_DIR/allow.txt
DENY=$BASE_DIR/deny.txt

(condor_status -pool collector.opensciencegrid.org:9619 -schedd -const '!isundefined(OSG_resource)' -f '%s\n' grid_resource | sed 's/^.* //' | sort | uniq)>$ALL.tmp
COUNT=$(cat $ALL.tmp | wc -l)
if [[ $COUNT -gt 0 ]]; then
    mv $ALL.tmp $ALL
fi

mkdir -p /tmp/ce-check
cd /tmp/ce-check
rm -f *.scitoken
rm -f $ALLOW.tmp
rm -f $DENY.tmp
while IFS= read -r LINE; do
    CE=$(echo "$LINE") 
    CE_HOST=$(echo $CE | tr ':' ' ' | awk '{print $1;}')
    echo
    echo "Checking $CE_HOST ..."
    /usr/sbin/frontend_scitoken $CE $CE >$CE.scitoken
    if _condor_SCITOKENS_FILE=$CE.scitoken _condor_SEC_CLIENT_AUTHENTICATION_METHODS=SCITOKENS _condor_TOOL_DEBUG=D_FULLDEBUG,D_SECURITY condor_ping -pool $CE -name $CE_HOST -type SCHEDD WRITE -verbose; then
        echo $CE_HOST >>$ALLOW.tmp
    else
        echo $CE_HOST >>$DENY.tmp
    fi
done <$ALL
mv $ALLOW.tmp $ALLOW
mv $DENY.tmp $DENY

